### ISSUE TITLE
Links to localhost:4000

### ISSUE THREAD

**Issue by jmoe** [codeforamerica/chimecms.org#3]
The ChimeCMS logo in the nav links to http://localhost:4000

Should probably go to the site root? :)

Just looking at the source for the page, looks like a few links to localhost:400 floating around.

**Comment by wpietri** [comment]
Thanks, that's a great point. Yes, we put that up a while back as a quick placeholder and haven't gotten back to it. I'll get on that right away.

**Comment by jmoe** [comment]
Looks like there's already a PR that got merged for this. So maybe just need to get pushed to production.

**Comment by wpietri** [comment]
Ok. Fixed! Thanks. By the way, we like the Trailhead backpacker-tag logo. Great stuff.

**Comment by jmoe** [comment]
:+1:
